# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/maxime/code/yaideaig

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/maxime/code/yaideaig

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maxime/code/yaideaig/CMakeFiles /home/maxime/code/yaideaig//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/maxime/code/yaideaig/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named yaideaig

# Build rule for target.
yaideaig: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 yaideaig
.PHONY : yaideaig

# fast build rule for target.
yaideaig/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/build
.PHONY : yaideaig/fast

src/attribut.o: src/attribut.cpp.o
.PHONY : src/attribut.o

# target to build an object file
src/attribut.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/attribut.cpp.o
.PHONY : src/attribut.cpp.o

src/attribut.i: src/attribut.cpp.i
.PHONY : src/attribut.i

# target to preprocess a source file
src/attribut.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/attribut.cpp.i
.PHONY : src/attribut.cpp.i

src/attribut.s: src/attribut.cpp.s
.PHONY : src/attribut.s

# target to generate assembly for a file
src/attribut.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/attribut.cpp.s
.PHONY : src/attribut.cpp.s

src/classes.o: src/classes.cpp.o
.PHONY : src/classes.o

# target to build an object file
src/classes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/classes.cpp.o
.PHONY : src/classes.cpp.o

src/classes.i: src/classes.cpp.i
.PHONY : src/classes.i

# target to preprocess a source file
src/classes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/classes.cpp.i
.PHONY : src/classes.cpp.i

src/classes.s: src/classes.cpp.s
.PHONY : src/classes.s

# target to generate assembly for a file
src/classes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/classes.cpp.s
.PHONY : src/classes.cpp.s

src/example.o: src/example.cpp.o
.PHONY : src/example.o

# target to build an object file
src/example.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/example.cpp.o
.PHONY : src/example.cpp.o

src/example.i: src/example.cpp.i
.PHONY : src/example.i

# target to preprocess a source file
src/example.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/example.cpp.i
.PHONY : src/example.cpp.i

src/example.s: src/example.cpp.s
.PHONY : src/example.s

# target to generate assembly for a file
src/example.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/example.cpp.s
.PHONY : src/example.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/readFile.o: src/readFile.cpp.o
.PHONY : src/readFile.o

# target to build an object file
src/readFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/readFile.cpp.o
.PHONY : src/readFile.cpp.o

src/readFile.i: src/readFile.cpp.i
.PHONY : src/readFile.i

# target to preprocess a source file
src/readFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/readFile.cpp.i
.PHONY : src/readFile.cpp.i

src/readFile.s: src/readFile.cpp.s
.PHONY : src/readFile.s

# target to generate assembly for a file
src/readFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/readFile.cpp.s
.PHONY : src/readFile.cpp.s

src/trainingSet.o: src/trainingSet.cpp.o
.PHONY : src/trainingSet.o

# target to build an object file
src/trainingSet.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/trainingSet.cpp.o
.PHONY : src/trainingSet.cpp.o

src/trainingSet.i: src/trainingSet.cpp.i
.PHONY : src/trainingSet.i

# target to preprocess a source file
src/trainingSet.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/trainingSet.cpp.i
.PHONY : src/trainingSet.cpp.i

src/trainingSet.s: src/trainingSet.cpp.s
.PHONY : src/trainingSet.s

# target to generate assembly for a file
src/trainingSet.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/yaideaig.dir/build.make CMakeFiles/yaideaig.dir/src/trainingSet.cpp.s
.PHONY : src/trainingSet.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... yaideaig"
	@echo "... src/attribut.o"
	@echo "... src/attribut.i"
	@echo "... src/attribut.s"
	@echo "... src/classes.o"
	@echo "... src/classes.i"
	@echo "... src/classes.s"
	@echo "... src/example.o"
	@echo "... src/example.i"
	@echo "... src/example.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/readFile.o"
	@echo "... src/readFile.i"
	@echo "... src/readFile.s"
	@echo "... src/trainingSet.o"
	@echo "... src/trainingSet.i"
	@echo "... src/trainingSet.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

